### ISSUE TITLE
segfault on mqtt:destroy()

### ISSUE THREAD

**Issue by vvzvlad** [tarantool/mqtt#15]
OS: Alpine Linux 3.5 (Linux as 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

Tarantool version: Tarantool 1.10.0-0-g42612ec04
MQTT lib version: 4adefc7bc45aaae776a677bbb0b54ecf7ec293f4

Case:
```
mqtt=require('mqtt')
m=mqtt.new()
m:connect()
m:destroy()

 Segmentation fault
  code: SEGV_MAPERR
  addr: 0x208
  context: 0x7f31be02f7c0
  siginfo: 0x7f31be02f8f0
  rax      0x0                0
  rbx      0x0                0
  rcx      0x2                2
  rdx      0x0                0
  rsi      0x1                1
  rdi      0x208              520
  rsp      0x7f31be02fe58     139851617992280
  rbp      0x41786ea8         1098411688
  r8       0x4                4
  r9       0x7f31be01fd80     139851617926528
  r10      0x55bfeefd4220     94282836689440
  r11      0x55bfeefd4270     94282836689520
  r12      0x208              520
  r13      0x1                1
  r14      0x40331000         1077088256
  r15      0x7f31bddfca10     139851615685136
  rip      0x7f31c262c2dc     139851691377372
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x208              520
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1532101361
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x55bfede1d479 in print_backtrace+9
#1  0x55bfedd4255a in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
#2  0x7f31c261fe17 in sigwaitinfo+8
Aborted (core dumped)
```

**Comment by dedok** [comment]
@vvzvlad can you send me codes please?
